### ISSUE TITLE
Package.json has main pointing to untranspiled file

### ISSUE THREAD

**Issue by Kelvur** [rubeniskov/i18njs#10]
![image](https://user-images.githubusercontent.com/16467804/49151107-46a3d080-f30f-11e8-8eea-15282f794e5e.png)
![image](https://user-images.githubusercontent.com/16467804/49151184-85398b00-f30f-11e8-8018-52946bee1bcb.png)

**Comment by rubeniskov** [comment]
https://github.com/rubeniskov/i18njs/pull/11
